AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation template deploys the Kittens Carousel static website on an Amazon Linux 2023 EC2 instance using the latest AL2023 AMI resolved through AWS Systems Manager Parameter Store. A custom security group allows HTTP traffic on port 80. The website files are downloaded from this GitHub repository and served by Apache HTTP Server.

Parameters:
  LatestAmiId:
    Description: Latest Amazon Linux 2023 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64:
            #! /bin/bash
            dnf update -y
            dnf install -y httpd wget
            FOLDER="https://raw.githubusercontent.com/eyupilhan/aws-ec2-static-website-cloudformation/main/static-web"
            cd /var/www/html"
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            wget ${FOLDER}/cat3.png
            systemctl enable --now httpd
Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL